# Save path.
#data_root_dir: '../testdataset/'
data_root_dir: '../dataset/'
# data_root_dir: '/data/fwb/dataset/'
# data_root_dir: 'D:\Pycharm\Projects\Experiments\PhD\testdataset\'
# data_root_dir: D:\PyCharm\Projects\Experiments\PhD\datasets\
# data_root_dir: /home/fengweibin/exps/testdataset

# Initialization.
random_seed: 1