# Task
task: seg

# Train/Val/Test data.
is_split: False
is_test_epoch: True
val_step: 3
min_val_epoch: 5

# Dataset info.
img_w: 346
img_h: 260

# To graph.
radius: 0.01
max_neighbors: 16
tw: 1.0e+3

# Data augments.
transform: False

# Initialization model.
shuffle: True
opt_name: sgd  # opts: adam, adamW, sgd
criterion_name: bce  # opts: smooth, cross, bce
epochs: 10  # 100--->5k
batch_size: 2
lr: 5.0e-2
weight_decay: 1.0e-4
momentum: 0.9

# Lr scheduler.
is_lr_scheduler: True
lr_scheduler: cycle  # opts: cosine, linear, step, cycle, lambda
warmup_epochs: 20
decay_epochs: 30
min_lr: 5.0e-6
warmup_lr_init: 5.0e-7
decay_rate: 0.1

# Graph conv.
sel_gnn: Spline  # opts: GCN, GAT, SAGE, GMM, Spline
gat_heads: 2
aggr: sum
kernel_size: 5
edge_attr_dim: 2
activation: relu

# Encoder.
enable_flash: False
enable_rope: True
in_chs: 1
enc_depths: [1, 1, 1]
enc_chs: [32, 64, 128]
enc_heads: [2, 4, 8]
enc_patches: [32, 32, 32]
enc_type: [M, M, T]
d_state: 8
d_conv: 3
expand: 1
drop_path: 0.3

# Dilated conv block.
xy_only: True
down_kernel_size: [3, 3, 3]
down_stride: [1, 2, 2]
num_sparse_block: [2, 1, 1]

# Graph pooling.
traceable: True
pooling_dim: [8, 6]  # [pool_x, pool_y]
pooling_aggr: max

# Decoder.
dec_depths: [1, 1]
dec_chs: [32, 64]
dec_heads: [2, 4]
dec_patches: [32, 32]
dec_type: [M, T]

# Metrics.
roc: True
pd_detT: 50
correct_thresh: 1.0e-4

# Classify head.
num_classes: 1
